account/urls.py

from django.contrib import admin
from django.urls import path
from . import views as v
urlpatterns = [
    path('register',v.adduser,name="reg"),
    path('login',v.login_view,name="login"),
    path('logout',v.logout_view,name="logout"),
    path('editprofile',v.edit_profile,name="editprofile"),
]

daily_icnome_expense/urls.py

from django.contrib import admin
from django.urls import path,include
from account.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path("acc-",include(("account.urls",'account'),namespace='account')),
    path("inc-",include(("income.urls",'income'),namespace='income')),
    path("exp-",include(("expense.urls",'expense'),namespace='expense')),
]

expense/urls.py

from django.contrib import admin
from django.urls import path
from .import views as v
urlpatterns = [
    path("add_expense",v.addexpense,name='add'),
    path("list",v.expense_list,name='list'),
    path("delete/<int:id>",v.delete_expense,name='delete'),
    path("ext/<str:ext>",v.sort_byexpense_type,name='ext'),
]

income/urls.py


from django.urls import path
from .import views as v
urlpatterns = [
    path("add_income",v.addincome,name='add'),
    path("list",v.income_list,name='list'),
    path("delet/<int:id>",v.delete_income,name='delete'),
    path("income_search",v.income_search,name="income_search")
]

account/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(forms.Form):
    username=forms.CharField(
        max_length=30,
         widget=forms.TextInput(attrs={'placeholder': 'Username'})
    )
    password=forms.CharField(max_length=30,widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )


class UserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email','password1','password2']

expense/models.py
from django.db import models

from django.contrib.auth.models import User
class Expense(models.Model):
    expense=models.IntegerField()
    expense_type=models.CharField(max_length=30)
    expense_date=models.DateField(auto_now=True)
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    class Meta:
        db_table="expense"

from django import forms

class ExpenseForm(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'

income/models.py
from django.db import models
from django.contrib.auth.models import User
class Income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    income_date=models.DateField()
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table="income"

from django import forms

class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields='__all__'

account/views.py
from multiprocessing import context
from django.shortcuts import redirect, render
from django.contrib.auth.forms import  UserCreationForm
from .models import LoginForm,UserForm
from income.models import Income
from expense.models import Expense
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User

def get_balance(request):
    uid=request.session.get("uid")
    incl=Income.objects.filter(user=uid)
    expl=Expense.objects.filter(user=uid)
    total_income=0
    total_expense=0
    for i in incl:
        total_income=total_income+i.income
    
    for i in expl:
        total_expense=total_expense+i.expense

    return total_income-total_expense


def home(request):
    context={"bal":get_balance(request)}
    return render(request,"home.html",context)

def adduser(request):
    if request.method=='POST':
        f=UserCreationForm(request.POST)
        f.save()
        return redirect("/")
    else:
        f=UserCreationForm()
        context={'form':f}
        return render(request,"adduser.html",context)

def login_view(request):
    if request.method=='POST':  
        uname=request.POST.get("username")
        passw=request.POST.get("password") 
        user=authenticate(request,username=uname,password=passw)
        if user is not None:
            request.session["uid"]=user.id
            login(request,user)
            return redirect("/")
        else: 
            f=LoginForm
            context={'form':f}
            return render(request,"login.html",context)
    else:
        f=LoginForm
        context={'form':f}
        return render(request,"login.html",context)


def logout_view(request):
    logout(request)
    return redirect("/") 

def edit_profile(request):
    uid=request.session.get("uid")
    u=User.objects.get(id=uid)
    if request.method=='POST':
        f=UserForm(request.POST,instance=u)
        f.save()
        return redirect("/")
    else:
        f=UserForm(instance=u)
        context={'form':f}
        return render(request,"updateuser.html",context)

expense/views.py
from django.shortcuts import redirect, render
from .models import Expense,ExpenseForm
from account.views import get_balance
def addexpense(request):
    if request.method=='POST':
        expense=request.POST.get("expense")
        if get_balance(request)>int(expense):
            f=ExpenseForm(request.POST)
            f.save()
            return redirect("/")
        else:
            f=ExpenseForm
            context={'form':f,'exp_msg':"Your Expense Amount Less Balance "}
            return render(request,"addexpense.html",context)
    else:
        f=ExpenseForm
        context={'form':f}
        return render(request,"addexpense.html",context)

def expense_list(request):
    uid=request.session.get("uid")
    explist=Expense.objects.filter(user=uid)
    expt=set()
    for i in explist:
        expt.add(i.expense_type)
    context={'expl':explist,'expt':expt}
    return render(request,"expenselist.html",context)

def delete_expense(request,id):
    inc=Expense.objects.get(id=id)
    inc.delete()
    return redirect("/")

def sort_byexpense_type(request,ext):
    uid=request.session.get("uid")
    explist=Expense.objects.filter(user=uid)
    expt=set()
    for i in explist:
        expt.add(i.expense_type)
    
    explist=Expense.objects.filter(user=uid,expense_type=ext)
    context={'expl':explist,'expt':expt}
   
    return render(request,"expenselist.html",context)

income/views.py

from django.shortcuts import redirect, render
from .models import Income,IncomeForm
from django.contrib.auth.models import User
def addincome(request):
    uid=request.session.get("uid")
    if request.method=='POST':
        income=request.POST.get("income")
        income_type=request.POST.get("income_type")
        income_date=request.POST.get("income_date")
        description=request.POST.get("description")

        inc=Income()
        inc.income=income
        inc.income_type=income_type
        inc.income_date=income_date
        inc.description=description
        inc.user=User.objects.get(id=uid)
        inc.save()
        return redirect("/")
    else:
        f=IncomeForm
        context={'form':f}
        return render(request,"addincome.html",context)

def income_list(request):
    uid=request.session.get("uid")
    inclist=Income.objects.filter(user=uid)
    context={'incl':inclist}
    return render(request,"incomelist.html",context)

def delete_income(request,id):
    inc=Income.objects.get(id=id)
    inc.delete()
    return redirect("/")

def income_search(request):
    uid=request.session.get("uid")
    srch=request.POST.get("srch")
    incl=Income.objects.filter(user=uid,description__contains=srch)
    context={'incl':incl}
    return render(request,"incomelist.html",context)

account/templates/adduser.html
{%extends 'sidebar.html' %} {%block body%}
<h1> User Registration form</h1>
<form method="post">
    {%csrf_token%}
    <table class="center" border="20" cellspacing="10" cellpadding="10">


        {{form.as_table}}
        <tr>
            <td>
                <input type="submit" value="Save">
            </td>
            <td>
                <input type="reset" value="Reset">
            </td>
        </tr>

    </table>
</form>
{%endblock%}

account/templates/home.html
 {%extends 'sidebar.html'%} {%block body%}

<h1>
    <i>Daily Income Expense Management</i></h1>
<p><i>Income Expense Management</i></Income>
</p>


{%if user.is_authenticated%}
<h2 style="color: rgb(6, 6, 216);"> Welcome : {{user}}</h2>
<h2 style="color:red"> Total Balance is : {{bal}} </h2>
{%endif%} {%endblock%}

account/templates/login.html
{%extends 'sidebar.html'%} {%block body%}
<header>
    <h1>Daily Income & Expense Tracker</h1>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        
        header {
            text-align: center;
            margin-bottom: 20px;
        }
        
        input[type="submit"],
        input[type="reset"] {
            padding: 10px 20px;
            margin: 10px;
            font-size: 20px;
            cursor: pointer;
            background-color: #758375;
            color: white;
            border: none;
            border-radius: 4px;
        }
        
        input[type="submit"]:hover {
            background-color: #458a48;
        }
        
        input[type="reset"]:hover {
            background-color: #f21010;
        }
    </style>

</header>
<form method="post">
    {%csrf_token%}
    <table class="center" border="20" cellspacing="40" cellpadding="30">
        {{form.as_table}}
        <tr class="center">
            <td><input type="submit"></td>
            <td><input type="reset"></td>

        </tr>
    </table>
</form>

{%endblock%}

account/templates/sidebar.html
{%load static%}
<link rel="stylesheet" href="{%static 'css/style.css' %}">

<div class="side">

    <h2><a href="/">Home</a></h2>
    {% if user.is_authenticated %}
    <h2><a href="{%url 'account:editprofile' %}">EditProfile</a></h2>
    <h2><a href="{%url 'income:add' %}">AddIncome</a></h2>
    <h2><a href="{%url 'expense:add' %}">AddExpense</a></h2>
    <h2><a href="{%url 'income:list' %}">IncomeList</a></h2>
    <h2><a href="{%url 'expense:list' %}">ExpenseList</a></h2>

    <h2><a href="{%url 'account:logout' %}">Logout</a></h2>

    {%else%}

    <h2><a href="{%url 'account:reg' %}">Register</a></h2>
    <h2><a href="{%url 'account:login' %}">Login</a></h2>

    {%endif%}




</div>
<style>
    .main {
        width: 100%;
        height: 700px;
        padding-top: 40px;
        padding: 1rem;
        margin: 5auto;
        background-image: url('{%static "images/4.jpg" %}')
    }
</style>



<div class="main" align="center">

    {%block body%} {%endblock%}

</div>

account/templates/updateuser.html
{%extends 'sidebar.html'%} {%block body%}
<h1> Edit Profile Form </h1>

<form method="post">
    {%csrf_token%}

    <table cellspacing="10" border="10">
        {{form.as_table}}
        <tr>
            <td><input type="submit" value="Update"></td>
            <td><input type="reset" value="Reset"></td>
        </tr>
    </table>

</form>
{%endblock%}

expense/templates/addexpense.html
{% extends 'sidebar.html' %} {%block body%}


<h1> Please Add Expense Information</h1>

{% if exp_msg %}
<script>
    alert("Expense Amount is Greater then balance")
</script>
{%endif%}

<form method="post">
    {%csrf_token%}
    <table border="10" cellspacing="10">
        {{form.as_table}}
        <tr>
            <td><input type="submit" value="Save"></td>
            <td><input type="reset" value="Reset"></td>
        </tr>
    </table>
</form>
{%endblock%}

expense/templates/expenselist.html
{%extends 'sidebar.html' %} {%block body%} {%if expl %}
<table border="10" cellspacing="10">
    <tr>
        <th>Id</th>
        <th>Expense</th>
        <th>ExpenseType</th>
        <th>ExpenseDate</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>

    {%for i in expl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.expense}}</td>
        <td>{{i.expense_type}}</td>
        <td>{{i.expense_date}}</td>
        <td><textarea cols="30" rows="2">{{i.description}}</textarea></td>
        <td>{{i.user}}</td>
        <td><a href="{%url 'expense:delete' i.id %}"> Delete</a></td>
        <td><a href=""> Edit</a></td>
    </tr>

    {%endfor%}
</table>

{%else%}
<h1> No Records Found ...</h1>
{%endif%}
<style>
    .rside {
        width: 250px;
        height: 100%;
        background-color: rgb(183, 227, 227);
        position: fixed;
        top: 0%;
        right: 0%;
        border: 4px solid #000;
        box-shadow: 5px 5px 15px rgba(116, 227, 64, 0.5);
    }
    
    h3 {
        padding: 10px;
        margin: 10px;
    }
</style>
<div class="rside">
    <h2>Sort By ExpenseType</h2>
    <h3><a href="{%url 'expense:list' %}">All</a></h3>
    {%for i in expt %}
    <h3><a href="{%url 'expense:ext' i %}">{{i}}</a></h3>
    {%endfor%}
</div>
{%endblock%}

income/templates/addincome.html
{%extends 'sidebar.html' %} {%block body%}

<h1> Please Add Income Information</h1>
<form method="post">
    {%csrf_token%}
    <table border="1">
        <tr>
            <th><label for="id_income">Income:</label></th>
            <td><input type="number" name="income" required id="id_income"></td>
        </tr>
        <tr>
            <th><label for="id_income_type">Income type:</label></th>
            <td><input type="text" name="income_type" maxlength="30" required id="id_income_type"></td>
        </tr>
        <tr>
            <th><label for="id_income_date">Income date:</label></th>
            <td><input type="text" name="income_date" required id="id_income_date" placeholder="Please Add  YYYY-MM-DD"></td>
        </tr>
        <tr>
            <th><label for="id_description">Description:</label></th>
            <td><textarea name="description" cols="40" rows="10" maxlength="300" required id="id_description">
</textarea></td>
        </tr>
        <tr>
            <th><label for="id_user">User:</label></th>
            <td><input type="text" name="uid" value="{{user}}"></td>
        </tr>
        <tr>
            <td><input type="submit" value="Save"></td>
            <td><input type="reset" value="Reset"></td>
        </tr>
    </table>
</form>
{%endblock%}

income/templates/incomelist.html
{%extends 'sidebar.html' %}

{%block body%}
<br>
<br>

<form method="post" action="{%url 'income:income_search'%}">
    {%csrf_token%}

    <textarea rows="3" cols="60" name="srch"></textarea>
    <input type="submit" value="Search">
</form>
<br>
<br>

{%if incl%}
<table border="1" cellspacing="10">
    <tr>
        <th>Id</th>
        <th>Income</th>
        <th>IncomeType</th>
        <th>IncomeDate</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>

    {%for i in incl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.income_type}}</td>
        <td>{{i.income_date}}</td>
        <td><textarea cols="30" rows="2">{{i.description}}</textarea></td>
        <td>{{i.user}}</td>
        <td><a href="{%url 'income:delete' i.id %}"> Delete</a></td>
        <td><a href=""> Edit</a></td>
    </tr>

    {%endfor%}
</table>

{%else%}
    <h1>No Record Found...</h1>
{%endif%}
{%endblock%}